name: test CI

on:
  push:
    tags:
      - 'release_backend_core'
      - 'release_backend_en'
      - 'release_backend_aps'
      - 'release_backend'
      - 'release_frontend'
      - 'release'

env:
  RELEASE_FRONTEND: ${{ (github.ref == 'refs/tags/release') || (github.ref == 'refs/tags/release_frontend') }}
  RELEASE_BACKEND_CORE: ${{ (github.ref == 'refs/tags/release') || (github.ref == 'refs/tags/release_backend') || (github.ref == 'refs/tags/release_backend_core') }}
  RELEASE_BACKEND_EN: ${{ (github.ref == 'refs/tags/release') || (github.ref == 'refs/tags/release_backend') || (github.ref == 'refs/tags/release_backend_en') }}
  RELEASE_BACKEND_APS: ${{ (github.ref == 'refs/tags/release') || (github.ref == 'refs/tags/release_backend') || (github.ref == 'refs/tags/release_backend_aps') }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: step 1 RELEASE_BACKEND_APS
        run: echo ${{ env.RELEASE_BACKEND_APS}}
      - name: step 2 RELEASE_BACKEND_CORE
        run: echo ${{ env.RELEASE_BACKEND_CORE}}
      - name: step 3 RELEASE_BACKEND_EN
        run: echo ${{ env.RELEASE_BACKEND_EN}}
      - name: step 4 RELEASE_BACKEND
        run: echo ${{ env.RELEASE_BACKEND}}
      - name: step 5 RELEASE_FRONTEND
        run: echo ${{ env.RELEASE_FRONTEND}}
      
      - name: step 1 RELEASE_BACKEND_APS
        run: echo ${{ env.RELEASE_BACKEND_APS}}
        if: ${{ env.RELEASE_BACKEND_APS}}
      - name: step 2 RELEASE_BACKEND_CORE
        run: echo ${{ env.RELEASE_BACKEND_CORE}}
        if: ${{ env.RELEASE_BACKEND_CORE}}
      - name: step 3 RELEASE_BACKEND_EN
        run: echo ${{ env.RELEASE_BACKEND_EN}}
        if: ${{ env.RELEASE_BACKEND_EN}}
      - name: step 4 RELEASE_BACKEND
        run: echo ${{ env.RELEASE_BACKEND}}
        if: ${{ env.RELEASE_BACKEND }}
      - name: step 5 RELEASE_FRONTEND
        run: echo ${{ env.RELEASE_FRONTEND}}
        if: ${{ env.RELEASE_FRONTEND}}
